### PR TITLE
Add YNH json app file with last commit as stable.

### PR DESCRIPTION
**Pull request by opi**
We could now use :

```
% yunohost app fetchlist --url=https://internetcu.be/internetcube.json --name=internetcube
% yunohost app install vpnclient
```

### CODE REVIEW

**Comment by opi** [comment]
Maybe json file could be simply named `apps.json`

**Comment by jvaubourg** [comment]
Very nice. But I think a lot a people use the web interface to install VPN Client and Wifi Hotspot. Is there a way to add this list to YunoHost directly into the Debian/YunoHost image, and view the apps in the web interface as official ones?

**Comment by opi** [comment]
Not sure how to add this list into the debian image. But we could tell people from local ISPs to run `yunohost app fetchlist --url=https://internetcu.be/internetcube.json --name=internetcube` when pre-installing cubes, right after doing postinstall ( Step 3 from https://yunohost.org/#/installation_brique_fr ).

**Comment by opi** [comment]
Hmm, actually there's a bug with this list. I'm inspired by json lists from https://github.com/yunohost/apps, but in fact json must contains `manifest` key for each app.
You can see differences between https://github.com/YunoHost/apps/blob/master/official.json and https://yunohost.org/official.json.
Maybe adding a raw json to this repo is not tha way to go, but instead writing some king of script to create a complete json.
Maybe @Kloadut can show us the script he uses on yunohost.org to process official.json and community.json

**Comment by Kloadut** [comment]
Done: https://github.com/YunoHost/apps/blob/master/list_builder.py

**Comment by opi** [comment]
https://github.com/YunoHost/apps/pull/9 allow us to use `list_builder.py` script to build full json file for internetcube apps.

**Comment by opi** [comment]
https://github.com/YunoHost/apps/pull/9 is reviewed & merged, thx to @Kloadut and @Psycojoker .

Now we could use `% python ./list_builder.py path/to/internetcube.json -o apps.json` to build a json file compatible with YunoHost  `app fetchlist` command.

We just have to:
- think about json filenames. Building `internetcube.json` to `apps.json` in my example is not perfect.
- Add a cron task on internetcu.be server to regularly build up json file.
- Document YunoHost  `app fetchlist` on internetcu.be

**Pull request merged**
