### PR TITLE
Conversion to middleman

### PR DESCRIPTION
**Pull request by randomstuff**
See #5 and #6.

### CODE REVIEW

**Comment by randomstuff** [comment]
It is currently setup to build two different sites (on for each language) so files may be duplicated beteen the two sites.

**Comment by Psycojoker** [comment]
At Neutrinet we are planning to start communicating in Dutch one day or another (thanks Belgium) so thinking about internationalization in a more flexible way might be a good idea (while it's better to have something working than to procrastinate on a complex problem).

Anyway, thanks a lot for your work :)

**Comment by randomstuff** [comment]
Yes, the current state of localization could be greatly improved. Do you have any idea of how you would like to handle localization?

Middleman has builtin support for i18n: the behavior is to build/serve separate localization in different folders (e.g. `/en/`, `/fr/`, `/nl/`). In order to have support for different domain names I currently build two versions of the site (one for each available localization). From this we could:
- Either, add support for `nl` in `http://internetcu.be/nl/`. This should be quite simple as this is the default behavior of middleman.
- Or we use one domain name for each locale (e.g. `labriqueinter.net`, `internetcu.be`, `nl.internetcu.be`), build them in a single directory (with per-locale sub-directories for i18n stuff) but and use nginx `try` directives in  order to pick the right files depending of the requested `Host`. We'd have to add some tweaks in order to do that but it should not be too much a pain. This way we could (if we want) merge the French version with the other versions.

I guess I'd choose the second solution if the tweaks are not too ugly.

Another (organizational) question is whether we **want** to build a single/centralized directory for all versions of the site or if we want to build different ones.

This should probably be forwarded/discussed in the mailing-list.

**Comment by randomstuff** [comment]
Rebased and added a new commit which allows to use a single build directory for all locales of the site:
- each locale should have its own domain name/virtual host;
- each locale is built in a `/{locale}/` subdirectory;
- some monkey-patching is used to make each locale think it is using `/`;
- a rack plugin is used to emulate TryStatic / nginx try;
- a rackup file (`config.ru`) is used to test the builded files;
- on nginx, each VirtualHost should have its own try directive.

TODO, add nginx configuration generator.

Some parts of this are slightly hackish because middleman i18n support is geared towards a single virtual host or all locales.

**Comment by randomstuff** [comment]
Should I rebase this stuff (or merge origin into it) in order to get it merged or should I close this? As I changed all the files, rebasing/merging will be slightly <s>PITA</s> boring (and more and more boring as additional commits come on top of master).

**Comment by randomstuff** [comment]
I guess we can close this.

**Comment by sbadia** [comment]
don't know, it would be cool to have this! ping @jvaubourg @Psycojoker wdyt ?
thanks @randomstuff for your work on this!

**Comment by Psycojoker** [comment]
Don't have strong opinion on that has we never really talked on how we want to communicate or even if we want to communicate for the website (which, for me comes before a technical solution). I remember that @jvaubourg had a stronger opinion on that.

**Comment by jvaubourg** [comment]
Keeping things the most simple possible is a good idea for me. Static HTML can not be more basic and, for now, especially with the wiki, we do not really need another solution.

**Pull request closed without merging**
