### PR TITLE
[enh] Allow to change the hypercube.sh script

### PR DESCRIPTION
**Pull request by zamentur**
Allow to change the new hypercube.sh file without creating new images https://dev.yunohost.org/issues/936

### CODE REVIEW

**Comment by zamentur** [comment]
Need to be tested

**Comment by zamentur** [comment]
pitchum says during the meeting this pr works :)

**Comment by sbadia** [comment]
Thanks!

**Comment by sbadia** [comment]
* https://repo.labriqueinter.net/install-sd.sh updated
* https://repo.labriqueinter.net/MD5SUMS updated too

**Pull request merged**
